---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vrixqmrn/dotta
    - export SOURCEPATH=/home/vrixqmrn/dotta_repo
    - /bin/cp -RT $SOURCEPATH $DEPLOYPATH
    # https://linuxize.com/post/cp-command-in-linux/